[versions]
agp = "8.11.2"
android-compileSdk = "36"
android-minSdk = "26"
android-targetSdk = "36"
androidx-activity = "1.12.3"
androidx-lifecycle = "2.9.6"
atomicfu = "0.31.0"
browser = "1.9.0"
buildkonfigGradlePlugin = "0.17.1"
componentsResources = "1.10.1"
composeHotReload = "1.0.0"
composeMultiplatform = "1.10.1"
dotenvKotlin = "6.5.1"
firebaseAnalyticsKtx = "22.5.0"
firebaseCrashlyticsKtx = "19.4.4"
foundation = "1.10.1"
androidCredentials = "1.5.0"
googleid = "1.2.0"
kotlinGradlePlugin = "2.2.0"
kotlinxDatetime = "0.7.1"
material3 = "1.9.0"
okio = "3.16.4"
powerSyncCore = "1.10.2"
reaktNativeToolkit = "0.22.1-SNAPSHOT"
runtimeVersion = "1.10.1"
sketchHttp = "4.3.1"
koinCompose = "4.1.1"
kotlin = "2.2.21"
ktorClientOkhttp = "3.3.3"
navigationCompose = "2.9.1"
datastore = "1.2.0"
kotlinx-serialization = "1.9.0"
googleServices = "4.4.4"
firebaseCrashlytics = "3.0.6"
connectivity = "2.3.0"
markdownRenderer = "0.38.1"
soloader = "0.12.1"
ttypic = "0.6.4"
ui = "1.10.1"

[libraries]
androidx-browser = { module = "androidx.browser:browser", version.ref = "browser" }
atomicfu = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "atomicfu" }
components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "componentsResources" }
firebase-analytics-ktx = { module = "com.google.firebase:firebase-analytics-ktx", version.ref = "firebaseAnalyticsKtx" }
firebase-crashlytics-ktx = { module = "com.google.firebase:firebase-crashlytics-ktx", version.ref = "firebaseCrashlyticsKtx" }
hermes-android = { module = "com.facebook.react:hermes-android" }
foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "foundation" }
jetbrains-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "runtimeVersion" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "material3" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
org-jetbrains-compose-ui-ui-tooling-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "ui" }
android-credentials = { module = "androidx.credentials:credentials", version.ref = "androidCredentials" }
android-credentials-play-services-auth = { module = "androidx.credentials:credentials-play-services-auth", version.ref = "androidCredentials" }
googleid = { module = "com.google.android.libraries.identity.googleid:googleid", version.ref = "googleid" }
powerSyncCore = { module = "com.powersync:core", version.ref = "powerSyncCore" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koinCompose" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koinCompose" }
koin-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koinCompose" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koinCompose" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-lifecycle-viewmodelCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtimeCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktorClientOkhttp" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktorClientOkhttp" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktorClientOkhttp" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktorClientOkhttp" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktorClientOkhttp" }
navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
connectivity-core = { module = "dev.jordond.connectivity:connectivity-core", version.ref = "connectivity" }
connectivity-device = { module = "dev.jordond.connectivity:connectivity-device", version.ref = "connectivity" }
connectivity-compose-device = { module = "dev.jordond.connectivity:connectivity-compose-device", version.ref = "connectivity" }
react-android = { module = "com.facebook.react:react-android" }
reakt-native-toolkit = { module = "de.voize:reakt-native-toolkit", version.ref = "reaktNativeToolkit" }
sketch-animated-gif = { module = "io.github.panpf.sketch4:sketch-animated-gif", version.ref = "sketchHttp" }
sketch-animated-gif-koral = { module = "io.github.panpf.sketch4:sketch-animated-gif-koral", version.ref = "sketchHttp" }
sketch-compose = { module = "io.github.panpf.sketch4:sketch-compose", version.ref = "sketchHttp" }
sketch-extensions-compose-resources = { module = "io.github.panpf.sketch4:sketch-extensions-compose-resources", version.ref = "sketchHttp" }
sketch-compose-resources = { module = "io.github.panpf.sketch4:sketch-compose-resources", version.ref = "sketchHttp" }
sketch-http = { module = "io.github.panpf.sketch4:sketch-http", version.ref = "sketchHttp" }
sketch-svg = { module = "io.github.panpf.sketch4:sketch-svg", version.ref = "sketchHttp" }
markdown-renderer-m3 = { module = "com.mikepenz:multiplatform-markdown-renderer-m3", version.ref = "markdownRenderer" }

## plugin
soloader = { module = "com.facebook.soloader:soloader", version.ref = "soloader" }
ttypic-plugin = { module = "io.github.ttypic:plugin", version.ref = "ttypic" }
buildkonfig-gradle-plugin = { module = "com.codingfeline.buildkonfig:buildkonfig-gradle-plugin", version.ref = "buildkonfigGradlePlugin" }
dotenv-kotlin = { module = "io.github.cdimascio:dotenv-kotlin", version.ref = "dotenvKotlin" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlinGradlePlugin" }
ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "ui" }
ui-tooling-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "ui" }


[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
composeHotReload = { id = "org.jetbrains.compose.hot-reload", version.ref = "composeHotReload" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlytics" }